.TH "eye" 1 "July 1, 2019" "eye 0.9.0-131b704/float64" "eye"
.SH NAME
eye
\- Configuration Lookup service
.SH SYNOPSIS
eye  [\-\-cpuprofile ] [\-\-memprofile ] [\-c|\-\-config /srv/eye/conf/eye.conf] [\-h|\-\-help] [\-\-version]
.SH DESCRIPTION
Eye stores threshold configuration profiles in a Format suitable for Cyclone metric monitoring.

.SH OPTIONS
.TP
\-\-cpuprofile 
write cpu profile to file
.TP
\-\-memprofile 
write memory profile to file
.TP
\-c,\-\-config /srv/eye/conf/eye.conf
Configuration file
.TP
\-h,\-\-help
Show usage message
.TP
\-\-version
Show version
.SH AUTHOR
Jörg Pernfuß
